### PR TITLE
Removes all deprecations and conforms to ember the last ember 1.x

### PR DESCRIPTION
**Pull request by Kilowhisky**
This does not repair tests. In order for tests to pass https://github.com/kurko/ember-localstorage-adapter/pull/130 has to be pulled in. But i tested the merge and the tests pass afterwards.

### CODE REVIEW

**Comment by bastimeyer** [comment]
@kurko 
Could you please merge this and #130, so we can get a new release with 1.13/2.0 support? Or are you waiting for a rebase of the pull requests?
The Ember and EmberData dependencies should also be updated to `~1.13.0 || ~2.0.0`.
Thanks!

**Comment by rzurad** [comment]
+1

**Comment by kurko** [comment]
Yes. I'll do it tonight.

**Comment by James1x0** [comment]
@kurko Any update on the merge?

**Comment by kurko** [comment]
Merged #130. Sorry for the delay. I'm looking for help in maintaining this project. I'll announce soon on Twitter who's going to replace me.

**Pull request merged**
